import moment from 'moment';
import { v4 as uuidv4 } from 'uuid';

export const taskData = [
	{
		id: uuidv4(),
		type: 'PICK-UP',
		description: 'Picking up a shipment',
		location: 'Pleasant Park',
		driver_id: 1,
		start_time: moment(new Date('2020-8-01')),
		end_time: moment(new Date('2020-8-01')).add(1, 'hour'),
	},
	{
		id: uuidv4(),
		type: 'DROP-OFF',
		description: 'Dropping off some items',
		location: 'Catty Corner',
		driver_id: 2,
		start_time: moment(new Date('2020-8-02')),
		end_time: moment(new Date('2020-8-02')).add(3, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'OTHER',
		description: 'Coffee break',
		location: 'The Authority',
		driver_id: 3,
		start_time: moment(new Date('2020-8-02')).add(6, 'hours'),
		end_time: moment(new Date('2020-8-02')).add(8, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'PICK-UP',
		description: 'Picking up some boxes',
		location: 'Sweaty Sands',
		driver_id: 1,
		start_time: moment(new Date('2020-8-02')).add(6, 'hours'),
		end_time: moment(new Date('2020-8-02')).add(10, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'DROP-OFF',
		description: 'Dropping off construction material',
		location: 'Retail Row',
		driver_id: 1,
		start_time: moment(new Date('2020-8-03')),
		end_time: moment(new Date('2020-8-03')).add(11, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'OTHER',
		description: 'Lunch break',
		location: 'Timmys',
		driver_id: 1,
		start_time: moment(new Date('2020-8-02')).add(11, 'hours'),
		end_time: moment(new Date('2020-8-02')).add(12, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'OTHER',
		description: 'Lunch break',
		location: 'Timmys',
		driver_id: 1,
		start_time: moment(new Date('2020-8-03')).add(11, 'hours'),
		end_time: moment(new Date('2020-8-03')).add(12, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'OTHER',
		description: 'Lunch break',
		location: 'Timmys',
		driver_id: 1,
		start_time: moment(new Date('2020-8-04')).add(11, 'hours'),
		end_time: moment(new Date('2020-8-04')).add(12, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'OTHER',
		description: 'Lunch break',
		location: 'Timmys',
		driver_id: 1,
		start_time: moment(new Date('2020-8-05')).add(11, 'hours'),
		end_time: moment(new Date('2020-8-05')).add(12, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'OTHER',
		description: 'Lunch break',
		location: "Mc Donald's",
		driver_id: 1,
		start_time: moment(new Date('2020-8-06')).add(11, 'hours'),
		end_time: moment(new Date('2020-8-06')).add(12, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'OTHER',
		description: 'Lunch break',
		location: "Mc Donald's",
		driver_id: 1,
		start_time: moment(new Date('2020-8-09')).add(11, 'hours'),
		end_time: moment(new Date('2020-8-09')).add(12, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'OTHER',
		description: 'Lunch break',
		location: "Mc Donald's",
		driver_id: 1,
		start_time: moment(new Date('2020-8-10')).add(11, 'hours'),
		end_time: moment(new Date('2020-8-10')).add(12, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'OTHER',
		description: 'Lunch break',
		location: "Mc Donald's",
		driver_id: 1,
		start_time: moment(new Date('2020-8-11')).add(11, 'hours'),
		end_time: moment(new Date('2020-8-11')).add(12, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'OTHER',
		description: 'Lunch break',
		location: "Mc Donald's",
		driver_id: 1,
		start_time: moment(new Date('2020-8-12')).add(11, 'hours'),
		end_time: moment(new Date('2020-8-12')).add(12, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'OTHER',
		description: 'Lunch break',
		location: "Mc Donald's",
		driver_id: 1,
		start_time: moment(new Date('2020-8-13')).add(11, 'hours'),
		end_time: moment(new Date('2020-8-13')).add(12, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'PICK-UP',
		description: '',
		location: '',
		driver_id: 2,
		start_time: moment(new Date('2020-8-13')).add(1, 'hour'),
		end_time: moment(new Date('2020-8-13')).add(5, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'DROP-OFF',
		description: '',
		location: '',
		driver_id: 2,
		start_time: moment(new Date('2020-8-10')).add(2, 'hours'),
		end_time: moment(new Date('2020-8-10')).add(7, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'OTHER',
		description: '',
		location: '',
		driver_id: 2,
		start_time: moment(new Date('2020-8-04')).add(2, 'hours'),
		end_time: moment(new Date('2020-8-04')).add(7, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'PICK-UP',
		description: '',
		location: '',
		driver_id: 3,
		start_time: moment(new Date('2020-8-03')),
		end_time: moment(new Date('2020-8-03')).add(8, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'DROP-OFF',
		description: '',
		location: '',
		driver_id: 3,
		start_time: moment(new Date('2020-8-05')),
		end_time: moment(new Date('2020-8-05')).add(12, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'OTHER',
		description: 'Vacation day',
		location: '',
		driver_id: 3,
		start_time: moment(new Date('2020-8-07')),
		end_time: moment(new Date('2020-8-07')).add(23, 'hours').add(59, 'minutes'),
	},
	{
		id: uuidv4(),
		type: 'DROP-OFF',
		description: 'Out of province drop off',
		location: '',
		driver_id: 3,
		start_time: moment(new Date('2020-8-14')),
		end_time: moment(new Date('2020-8-14')).add(12, 'hours'),
	},
	{
		id: uuidv4(),
		type: 'PICK-UP',
		description: 'Out of province pick up',
		location: '',
		driver_id: 1,
		start_time: moment(new Date('2020-8-11')),
		end_time: moment(new Date('2020-8-11')).add(9, 'hours'),
	},
];
